### ISSUE TITLE
AM/PM defaults to AM

### ISSUE THREAD

**Issue by srushik** [nehakadam/DateTimePicker#17]
When using the format "mm-dd-yyyy hh:mm:ss AA"

The DateTimePicker always defaults to AM regardless of AM/PM entered for the date.

![image](https://cloud.githubusercontent.com/assets/9254024/4648040/3cc9c1e2-547f-11e4-8d0e-96c38b1a4c1e.png)

**Comment by srushik** [comment]
After looking at the file DateTimePicker.js it appears as if the issue is on line 697
dtPickerObj.dataObject.dCurrentDate = dtPickerObj._parseDateTime(sCurrent);

The value sCurrent correctly displays the PM.
But, the valued tPickerObj.dataObject.dCurrentDate is converted to GMT and drops the PM making it AM.

I don't know what the fix would be.

**Comment by srushik** [comment]
I found a way to make the AM/PM work correctly, but I don't know if these edits cause an adverse effect on the functionality.

In the file DateTimePicker.js:

<hr>

Line   546:                 dtPickerObj.dataObject.bIs12Hour = true;

Line 1233:                  //else
Line 1234:                  //{
Line 1235:                      sTime = sArrDateTime[1];
Line 1236:                  //}

<hr>
1. Change the variable dtPickerObj.dataObject.bIs12Hour to =true
2. Comment out the else statement, but leaving the sTime=sArrDateTime[1];

It appears as though "sTime" should be assigned regardless whether the if statement is true or false and should not be inside the else.  As written, if the "IF" statement is true, then the sTime value is never assigned.

I would love to hear from a developer on this issue to know if this edit is valid or if there is a more appropriate fix, to display the AM/PM correctly.

**Comment by lajpatshah** [comment]
Hello

Please give us a couple of days to revert.

Thanks

Lajpat

**Comment by nehakadam** [comment]
Hello,

Thanks for pointing out the error in the DateTimePicker.
1. The issue was because a line of code for setting a value of `dtPickerObj.dataObject.bIs12Hour` was   written after `_parseTime` and `_parseDateTime` function calls in the `_showPicker` function. So, I changed it's position before those function calls.

For `_parseTime` function call

```

    dtPickerObj.dataObject.bIs12Hour = dtPickerObj._compare(dtPickerObj.dataObject.sTimeFormat,  
    dtPickerObj.dataObject.sArrInputTimeFormats[0]);
    dtPickerObj.dataObject.dCurrentDate = dtPickerObj._parseTime(sCurrent);

```

For `_parseDateTime` function call

```

    dtPickerObj.dataObject.bIs12Hour =     
    dtPickerObj._compare(dtPickerObj.dataObject.sDateTimeFormat, 
    dtPickerObj.dataObject.sArrInputDateTimeFormats[1]) ||  
    dtPickerObj._compare(dtPickerObj.dataObject.sDateTimeFormat, 
    dtPickerObj.dataObject.sArrInputDateTimeFormats[3]) || 
    dtPickerObj._compare(dtPickerObj.dataObject.sDateTimeFormat,   
    dtPickerObj.dataObject.sArrInputDateTimeFormats[5]) || 
    dtPickerObj._compare(dtPickerObj.dataObject.sDateTimeFormat, 
    dtPickerObj.dataObject.sArrInputDateTimeFormats[7]);
    dtPickerObj.dataObject.dCurrentDate = dtPickerObj._parseDateTime(sCurrent);

```
- There is no need to make changes for `_parseTime` function call because `dtPickerObj.dataObject.bIs12Hour` parameter is not used in `_parseTime` function definition.
1. Made changes in `_parseDateTime` function
   - Changed line `var sTime;`  to `var sTime = sArrDateTime[1];`
   - Removed `else` block of condition `if(dtPickerObj.dataObject.bIs12Hour)`

Your solution to this issue is correct. But setting a value of parameter `dtPickerObj.dataObject.bIs12Hour` before using it will be logically correct.

Check [Formats Example](https://github.com/CuriousSolutions/DateTimePicker/blob/master/demo/Format-Both.htm)

Thank you.

**Comment by srushik** [comment]
Works great.  Thank you.

**Comment by yejihan** [comment]
I don't think the issue has been resolved completely.
When using the format "hh:mm AA" if you set it "12:30PM" the DateTimePicker defaults to 12:30AM regardless of AM/PM entered for the date.

**Comment by nehakadam** [comment]
Hello,

Yes, this issue occurs only when time value is between `12:00 PM` and`12:59 PM`.
I have changed `if(dtPickerObj._compare(sMeridiem, "PM"))` to `if(iHour < 12 && dtPickerObj._compare(sMeridiem, "PM"))`. You can download updated DateTimePicker.js

Thank You.

**Comment by yejihan** [comment]
Hi Neha.
Thank you very much for resolving this issue so quickly. You saved my day.
It works great now!
